/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class orthae_com_github_windowsspeech4j_SpeechDriverAdapter */

#ifndef _Included_orthae_com_github_windowsspeech4j_SpeechDriverAdapter
#define _Included_orthae_com_github_windowsspeech4j_SpeechDriverAdapter
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_initialize
  (JNIEnv *, jobject);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    setVolume
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_setVolume
  (JNIEnv *, jobject, jshort);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    getVolume
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_getVolume
  (JNIEnv *, jobject);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    setRate
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_setRate
  (JNIEnv *, jobject, jshort);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    getRate
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_getRate
  (JNIEnv *, jobject);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    setVoice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_setVoice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    getVoices
 * Signature: ()[Lorthae/com/github/windowsspeech4j/Voice;
 */
JNIEXPORT jobjectArray JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_getVoices
  (JNIEnv *, jobject);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_speak
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
