/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class orthae_com_github_windowsspeech4j_SpeechDriverAdapter */

#ifndef _Included_orthae_com_github_windowsspeech4j_SpeechDriverAdapter
#define _Included_orthae_com_github_windowsspeech4j_SpeechDriverAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_initialize
	(JNIEnv *, jobject);

/*
 * Class:     orthae_com_github_windowsspeech4j_SpeechDriverAdapter
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_orthae_com_github_windowsspeech4j_SpeechDriverAdapter_speak
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
